# Generated by Django 5.2 on 2025-05-09 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('overview', models.TextField()),
                ('technical_details', models.TextField()),
                ('key_features', models.TextField()),
                ('gallery', models.ImageField(upload_to='project_gallery/')),
                ('chalenges_solution', models.TextField()),
                ('results_impact', models.TextField()),
                ('content', models.TextField()),
                ('completed_date', models.DateField(default=django.utils.timezone.now)),
                ('skills', models.ManyToManyField(to='main_page.skill')),
            ],
        ),
    ]
