# Generated by Django 5.2 on 2025-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='project_gallery/'),
        ),
    ]
