# Generated by Django 5.2 on 2025-05-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_skill_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
    ]
