# Generated by Django 5.2 on 2025-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_remove_project_content_alter_project_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='game', max_length=100),
            preserve_default=False,
        ),
    ]
