# Generated by Django 5.2 on 2025-05-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='project',
            name='key_features',
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.ManyToManyField(to='main_page.feature'),
        ),
    ]
