# Generated by Django 5.2 on 2025-05-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_feature_skill_importance_remove_project_key_features_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='chalenges_solution',
            new_name='challenges_solution',
        ),
    ]
